### ISSUE TITLE
STORE:  EDIT PRODUCT

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#100]
Regardless of how the product is configured, you should be returned to the Products Overview Table whenever you submit after editing a product.  Right now it just returns you to the same product details screen and then you have to use the left-side navigation to get back to the Products table.

**Comment by timeforcamp** [comment]
this is due to the need to submit the product in order to show the option variants table. we can send them back to the products table but that would mean they would need to edit the product again to see the options variants.

**Comment by DENICHOLS** [comment]
Are you not able to determine that the submit is being done from the EDIT function in the first place and then route based on the source of the submission?

New Product Path: https://test.timeforcamp.com/products/new
Edit Product Path: https://test.timeforcamp.com/products/102/edit

**Comment by DENICHOLS** [comment]
I thought that you were going to add a link under the inventory section that would point to an anchor set on the options table.
