### ISSUE TITLE
STORE PAGE - User View - smaller product cards?

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#102]
I know that screen size will be the main player here, but if we make the cards smaller, could we better utilize the available horizontal real estate on the page and potentially get more cards left to right before wrapping to the next row?

![image](https://user-images.githubusercontent.com/13508954/74463892-2d296e80-4e58-11ea-9f29-35da854bd519.png)

**Comment by timeforcamp** [comment]
reduced the size of the picture and the cards.
