### ISSUE TITLE
CHECKING IN

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#104]
I had a camper who was owed several store products.  However, I just marked him as Checked-in without marking the products as delivered and now I have no way of going in to mark his products as delivered.

**If you check them in with pending items...**
1) Turn the row yellow so that it stands out in the camper table
2) Allow admin to go in and update the deliverables
3) Maybe disable the CHECK-IN slider as well

**Comment by timeforcamp** [comment]
<img width="1391" alt="Screen Shot 2020-02-14 at 9 20 44 AM" src="https://user-images.githubusercontent.com/6132268/74543677-6a9b0400-4f0b-11ea-83dc-f50a34ec3e0a.png">
