### ISSUE TITLE
ORDER SUMMARY: Transaction Log Purpose

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#108]
The transaction log in the order summary seems to be a mix between revenue and balance now. 

 If the purpose of the transaction log is to show how we calculated everything up so that it matches the amount paid then we should only show negative numbers if a refund is issued.  Right now admin fees are showed as a positive, but store item fees are a negative even though we retain both of those fees.

If the purpose is to show revenue...then we should show administration fees and store item fees as negative numbers so that the balance in the transaction log matches the revenue that the camp will receive as referenced in the camper list under the revenue column.

Right now, we have a mix because we show the administration fee as a positive, but the store item fees are a negartive, but both items are retained by TFC.  Consequently, the amount paid does not match the transaction log balance.  

$262 vs. $261. 
 **I think that the product should be shown on two lines that match the total paid for the product.**
1) Camp price ($20.00)
2) Store fee ($1.00)

**Ultimate question...what does BALANCE in the table mean?  Amount Paid (by camper) or Amount Earned (by camp)**  **Right now it is neither!**

![image](https://user-images.githubusercontent.com/13508954/74537215-476a5780-4eff-11ea-9330-404e7307b4dc.png)

**Comment by timeforcamp** [comment]
In your picture if you look one line down it has the the balance as 262.00 which is the store purchase plus the admin fee we applied. The store item fee is new and it has to be there.

**Comment by DENICHOLS** [comment]
If it has to be there...then either it needs to be a positive like the admin fee, or we need to make the admin fee negative.  It is a mixed bag right now.  It all comes down to purpose of that table.  Who is it for, and what is the purpose?
