### ISSUE TITLE
Monthly Registrations Widget Adjustment

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#11]
Y Axis data is crowded and needs to adjust to larger horizontal values (like in 5's or 10's) to account for larger quantities of registrations.

![image](https://user-images.githubusercontent.com/13508954/57631317-e1facc00-7564-11e9-84a5-c52003f4096b.png)

**Comment by timeforcamp** [comment]
This was fixed in a previous build.
