### ISSUE TITLE
Order Summary: Items List (left side table)

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#114]
Is it possible to either indent the Products table under the camper to which it applies OR indicate on the product which camper it applies to?  Right now the product falls under the camper and it may be missed that it belongs to the camper above.

![image](https://user-images.githubusercontent.com/13508954/74590503-9c2bd200-4fd4-11ea-8109-50c2c7d206b0.png)

This would be similar to how you display it in the right-side column by indenting products under the registration to which they apply

![image](https://user-images.githubusercontent.com/13508954/74590791-44db3100-4fd7-11ea-882e-57fa7e9a4ca8.png)

**Comment by timeforcamp** [comment]
With the new order summary layout is this an issue still?
