### ISSUE TITLE
Revenue vs. Paid In Full on Camp Table

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#115]
The camp table has two columns...revenue and Paid In Full...that currently report different information.

Revenue is all revenue (registrations and store items), while Paid In Full is only registrations.

In this case, I had a camper who was paid in full with store items, but I refunded the camper registration.  This left only the $20 store item, which was already paid in full.  However, that is not reflected on the table in the Paid In Full column.

**Shouldn't PAID IN FULL reflect all items that truly paid in full and not just registration items?**

![image](https://user-images.githubusercontent.com/13508954/74590598-69360e00-4fd5-11ea-9397-13b79cac1472.png)

**Comment by timeforcamp** [comment]
"Revenue is all revenue (registrations and store items), while Paid In Full is only registrations." not an accurate statement. 

This is just a bug in the paid in full not including the store items revenue.
