### ISSUE TITLE
Installment Agreement: User View (View Order)

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#116]
What is the meaning of the number, or should it not be there?

![image](https://user-images.githubusercontent.com/13508954/74590843-d185ef00-4fd7-11ea-82df-455860864db8.png)

**Comment by DENICHOLS** [comment]
Why is the number there?

**Comment by timeforcamp** [comment]
What screen is this on?

**Comment by DENICHOLS** [comment]
Logged in as a user.  View Order.
