### ISSUE TITLE
REFUND: Store items missing in right table when doing a refund on camp registration

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#119]
Registration with store products.  Went to refund the registration and noticed that store items are not referenced in the right table, but the subtotal calculates as if they are there.

![image](https://user-images.githubusercontent.com/13508954/74592119-c3d66680-4fe3-11ea-8657-e2a278292802.png)

**Comment by DENICHOLS** [comment]
The right side table shows a subtotal of $246, but the items above it only account for $225.  That is because the store items are not being referenced on the screen when you go in to do a refund.

**Comment by timeforcamp** [comment]
Refund of a what? What screen are you on? How did you get there? There are several refund screens.

**Comment by timeforcamp** [comment]
I think i found where this was, check the next build.
