### ISSUE TITLE
STORE:  Can't add a store item to the cart as part of the registration flow if that same item already exists in the cart as a stand-alone purchase

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#134]
I was logged in as a customer account and added an item from the store into my shopping cart.  I then went through the process of adding a registration to my cart, but when I got to the store, and tried to add the same item to my registration that was already in my cart, I received the following message:

![image](https://user-images.githubusercontent.com/13508954/74868620-28fbc600-531c-11ea-9f94-f649ec3cd210.png)

I think I know why it won't add it to the cart, but think that the message needs to be adjusted as it indicates that the available qty has been exceeded...but in this case, the item qty is not being tracked...it is just IN STOCK.  

We just need to discuss what the message should say and whether or not there are other scenarios that would warrant a slightly different message.

**Comment by timeforcamp** [comment]
Is this still an issue?
