### ISSUE TITLE
Add "How Did You Hear About Us" as optional item to add on camp registration form

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#14]
Provide the camp administrator with the ability to include a "How Did You Hear About Us" question on the registration form.  This would be under the additional information section where T-shirt size, insurance information, etc. is located.

Instead of an open text field, provide either a single select or multi-select field to include:

Word of mouth
Promotional Flyer / Poster
Instagram
Facebook
LinkedIn
Twitter
Radio
Television

**Comment by timeforcamp** [comment]
This is targeted for the August release.

**Comment by timeforcamp** [comment]
Released into production during our August Release.
