### ISSUE TITLE
Attendee Registration form: Default image placeholder missing

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#144]
The **DEFAULT** image is missing next to the Attendee Image.  It helps to have it there to catch the users eye as they are entering data.

![image](https://user-images.githubusercontent.com/13508954/90773213-32f68580-e2bb-11ea-8e2d-83e9ca4a88a4.png)

**Comment by timeforcamp** [comment]
This is no longer valid.
