### ISSUE TITLE
Hide Tax ID on customer VIEW ORDER screen if it does not exist

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#147]
Some entities don't have to provide us with a TAX ID.  We need to hide the reference to it on the Customer View Order screen if it not provided by the organization.

![image](https://user-images.githubusercontent.com/13508954/90776198-6a673100-e2bf-11ea-8749-83d0f8e3de29.png)

And on the PRINT screen as well

![image](https://user-images.githubusercontent.com/13508954/90776348-9bdffc80-e2bf-11ea-9835-d1695d58ac24.png)

**Comment by timeforcamp** [comment]
Also corrected in print order screen.

**Comment by DENICHOLS** [comment]
The empty tax id is still visible on both screens.

**Comment by timeforcamp** [comment]
hasn't been pushed to test yet.
