### ISSUE TITLE
Event Store: Product Colors

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#148]
When I added my item to the store....the COLOR option was already there with a forced format of GRID.  I entered my color names but chose not to enter actual colors.  Consequently, the result for the end user looks like this:

![image](https://user-images.githubusercontent.com/13508954/90776580-e3ff1f00-e2bf-11ea-9267-b56587c5a6d4.png)

I know that the problem is that we can put validation on those fields, but if it triggers a validation response....ALL IMAGES on the product page that were not already saved will have to be re-uploaded.  (not the best user experience...but nothing we can really do about it)

Sooooo....can we put a message on that card that gives direction for the user?  I know it's a bit long, but I think it is clear!

- Note: The grid format for colors expects you to provide the color name as well as a picture associated to that color (either an actual image of the product or a color square).  If you do not want to provide images of your color choices, please close the COLOR option with the X, and then add a new Color option where only the color names are expected.

**Comment by timeforcamp** [comment]
This is no longer valid.
