### ISSUE TITLE
Ability to allow for reserved registration into a team camp event

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#15]
Provide the ability to limit who can register for a specific team camp event to only those who have the appropriate code to access the registration form, and give the team coach the ability to see which of his/her athletes have already registered by creating a new limited view only role that can be set by the camp administrator.

**Comment by timeforcamp** [comment]
This is targeted for our August release.

**Comment by timeforcamp** [comment]
Feature has been released to Test and is in UAT.

**Comment by timeforcamp** [comment]
Released into production during August Release Control.
