### ISSUE TITLE
Medication & Dosage Information: Wording Consistency Needed: 

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#151]
On the registration form visible to attendee:

Change: Only required if you need camp staff to administer the medication to the camper. Otherwise, please enter N/A.

To: Only required if you need event staff to administer the medication to the event attendee. Otherwise, please enter N/A.

**Comment by DENICHOLS** [comment]
You deleted the comment completely.  Please add back as follows:

Only required if you need event staff to administer the medication to the event attendee. Otherwise, please enter N/A.

**Comment by timeforcamp** [comment]
It is there... when you turn off validation the message is not present. Are you certain the validation is enabled on this field? In test:
![image](https://user-images.githubusercontent.com/6132268/92391196-d3cda900-f0e1-11ea-9104-78d348463408.png)
