### ISSUE TITLE
Vendor Side: Size information changes needed

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#156]
Remove the errant periods.
Change "colors" to sizes

**Change wording under Header Row:**
The first row of data contains attribute names, separated by a comma, similar to the header row on a table.  Each subsequent row contains values associated to the attribute names.  Ex.  First row (size, size code) / second row (Youth Small, YS) / third row (Adult X-Large, XL), and so on.

**Change wording for Size, Code examples**
Size: The size option the customer sees when ordering.  Ex: Adult X-Large
Code: The value your organization uses to identify the size. Ex: XL

![image](https://user-images.githubusercontent.com/13508954/91085383-ff955d00-e612-11ea-9b18-5410aaf4b0e4.png)

**Comment by DENICHOLS** [comment]
Remove the following lines.  May not have been evident in my first post.

It is very important the header row matches the format specified below exactly. .

Every size you want to load into Time For Camp has a row and each attribute matches the header row. If there is no information for a given attribute just leave it blank..

**Comment by timeforcamp** [comment]
I left them on purpose.
