### ISSUE TITLE
Vendor side: Import Colors  - wording changes needed

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#157]
**Remove errant periods**

**Change wording under Header Row:**
The first row of data contains attribute names, separated by a comma, similar to the header row on a table. Each subsequent row contains values associated to the attribute names. Ex. First row (color, color code) / second row (Royal Blue, RB) / third row (Forest Green, FGr), and so on.

**Change wording for Color, Code examples**
Color: The color option the customer sees when ordering. Ex: Royal Blue
Code: The value your organization uses to identify that color. Ex: RB

**Comment by DENICHOLS** [comment]
Get rid of these lines:  This may not have been evident in my first post.

It is very important the header row matches the format specified below exactly. .

Every color you want to load into Time For Camp has a row and each attribute matches the header row. If there is no information for a given attribute just leave it blank..

**Comment by timeforcamp** [comment]
I left them on purpose.
