### ISSUE TITLE
Folders: Moving item from folder/sub-folder back to the main screen (

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#159]
The system is very intuitive in how to move an event/product/camper from the main screen into a folder, and from a folder into additional folders.  However, it is not very obvious how to remove an item from all folders and return it to the main screen.

You basically have to select to MOVE the item and then just say MOVE HERE to get it out of the folders.  But most people won't get that!  

Can we have an option like "Remove from all folders" or something?

**Comment by DENICHOLS** [comment]
There is still no obvious option for removing an item from a folder in which it has been placed.

**Comment by timeforcamp** [comment]
There is a new menu option that says ‘remove from folders?’
