### ISSUE TITLE
Enhanced search/filter capability within camp registrations

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#16]
Add the ability to do searches & filter across all camps within the organization so that you can drill down to specific data sets of interest and then export the results as opposed to only being able to export the raw data into Excel and having to manipulate it there.

Should be able to select the camps that you want to include and then determine the parameters by which you want to search/filter that information.

Also need to be able to determine whether or not to include closed camps vs. open camps vs. all camps in the data.

**Comment by timeforcamp** [comment]
This is targeted for our August release.

**Comment by timeforcamp** [comment]
Released into production during our August Release.
