### ISSUE TITLE
Modify PRINT ROSTER fields

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#165]
Eliminate sign-in/sign-out columns and replace with Free Product column to account for the item selected during registration that is offered for free/upcharge.

Columns should be"
Picture, Attendee, Age/Grade, Gender, Allergies, Best Contact, **FREE/UPGRADE ITEMS**, **STORE PURCHASES (currently listed as ITEMS)**

![image](https://user-images.githubusercontent.com/13508954/92243074-77228200-ee86-11ea-9ec0-c931216293c6.png)

**Comment by timeforcamp** [comment]
The print roster form is not the place for this. The check-in campers screen already has this functionality and is intended to be used for product distribution..

**Comment by DENICHOLS** [comment]
At this time there is no single place where I can see an overview of all of the free products I need to pull for my camp as a whole, the store purchases that I need for my camp as a whole, or even the Add-Ons that apply to each camper.

The print roster shows me store purchases, but not free/upgrade products.  There is not currenlty an option to see those across the entire camp...I have to go one camper at a time.  Standard products are not shown at the camp level...only Vendor products.  And for add-ons I have to run a separate report just to see those.

We need to figure out WHERE the camp admin can pull this information in a single report for easier and faster reference.

**Comment by timeforcamp** [comment]
The check-in campers does this but it sorts by the camper. You can see each camper and the items (products and add-ons) that each camper has purchased for the entire event. That can be filtered by team as well. 

I am closing this as we have enhancement request #171 for a report that can be run that will allow the sort to happen based on each product or add-on.
