### ISSUE TITLE
Reports: throws validation error on both report types

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#166]
But the error is not presented to the user...only the message "Please review the problem below"

**Comment by timeforcamp** [comment]
FINALLY recreated this in production, doesn't seem to be broken on my local machine or test. One thing to note is that t-shirt size is no longer a valid field as we took that away. So the report for Kyler Chan for t-shirt size is not valid any longer.

Will also add a report to the backlog for products. Need a report that shows the attendees and the products they purchased. We have this in the admin view for checkin campers but might be nice as a report.
