### ISSUE TITLE
Prevent user from seeing a store during the registration flow when the store is open, but no products are visible

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#169]
In this example, the store is OPEN and presented to the registration flow, but there are no products that are marked as visible in the store.

I think we should just bypass the store in this scenario.

![image](https://user-images.githubusercontent.com/13508954/92372300-59d9f780-f0c2-11ea-88d8-927325dce2f4.png)

**Comment by timeforcamp** [comment]
Why would this ever happen?  This is on the event admin to ensure they have products when the show the store feature in the event. The product works as designed.
