### ISSUE TITLE
Shopping Cart total not matching Totals Table and amount due

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#173]
Shopping cart includes $125 camp registration and $5.00 shirt upgrade.  But subtotal on the right shows $124.59 and is not calculating properly.  Accordingly, the admin fee, tax, and total due are all off.

![image](https://user-images.githubusercontent.com/13508954/92790102-178a1200-f371-11ea-9235-1b942c0ecd66.png)

The order receipt shows that I paid the correct amount though:

![image](https://user-images.githubusercontent.com/13508954/92797268-88ccc380-f377-11ea-827a-561b548ad9b7.png)

**Comment by timeforcamp** [comment]
This was an outstanding #todo in regards to tax calculations related to up-charged products embedded within the camp registration flow.
