### ISSUE TITLE
Back and Next button consistent look needed

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#179]
Back/Next buttons are not presented consistently throughout the site...some short, medium and 1/2 page in size
Reg/Store - short
Order Summary - Medium
SHopping cart/checkout/pay - 1/2 screen

![image](https://user-images.githubusercontent.com/13508954/93952078-92f2a880-fd0d-11ea-8316-03a01d457eae.png)

![image](https://user-images.githubusercontent.com/13508954/93952007-6c347200-fd0d-11ea-8b1b-fcbd427a76bb.png)

![image](https://user-images.githubusercontent.com/13508954/93952038-7eaeab80-fd0d-11ea-9a7b-d4851bb0a404.png)

**Comment by timeforcamp** [comment]
In current build.
