### ISSUE TITLE
Set text-decoration:none on phone number in the organization footer on sites/app to prevent link color change

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#182]
This appears to only be an issue in Safari, but once you click the phone number it turns blue as a clicked link, which is then lost on the darker backgrounds.  It should still be a link, but just needs to have text-decoration set to none in the style tag.

**Comment by timeforcamp** [comment]
This was due to the phone number not being a hyper-link. Added the hyper-link and changed, text-decoration and coloring.
