### ISSUE TITLE
Add organization logo to left of order information on customer orders page

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#184]
Now that we limit orders to a single organization, it would be nice to add the org logo to the left of each order on the customer order's page...similar to how you show the product picture to the left of each item in the shopping cart. (https://test.timeforcamp.com/orders)

![image](https://user-images.githubusercontent.com/13508954/94087370-2b9f2c00-fdd3-11ea-91e2-c9d7b81054ca.png)

**Comment by timeforcamp** [comment]
In next build.
