### ISSUE TITLE
Something weird happening with the map.  Maybe just kill the map and leave the address since map can't be used to get directions anyways.

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#185]
Getting rid of the map would shave several inches from the footer.  

Notice that the Addresses are identical, but the results are different.

This is the map when viewing EVENT DETAILS on APP for Wall ISD.  
![image](https://user-images.githubusercontent.com/13508954/94087663-fd6e1c00-fdd3-11ea-8d8d-a5205a5c6bf3.png)

This the map when viewing EVENT DETAILS on SITES & APP for Regression Test organization

![image](https://user-images.githubusercontent.com/13508954/94087745-2c848d80-fdd4-11ea-99c3-b451e8b01863.png)

**Comment by timeforcamp** [comment]
Removed the map but created a link with the address that opens to directions in the appropriate app on a mobile device or google on desktop.
