### ISSUE TITLE
Gandy: Fulfillment Receipts Branding

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#192]
Fulfillment receipts should be branded with whatever logo/name we end up settling on with Gandy....not just the current Gandy logo.  Given the volume that they will be churning out...it is an opportunity for us to be represented with some free marketing

GoEventsOnline by Gandy Ink (powered by Time For Camp)......or whatever it ends up being

**Comment by timeforcamp** [comment]
This is already the design. Just waiting on the logo from the vendor.
