### ISSUE TITLE
Vendor: Onboarding

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#193]
•	Give Vendor ability to onboard a new customer through our backend...need to include:

- the Vend Account Number

- first name, last name, email address, sitename

-	normal wizard questions
Vendor may not have their EIN on file (no reason to)
•	We could add this as part of verification process and not require it from them
-	capture user who onboarded them and list it on new customer details page
-	need automated notification to us so that we can follow up for verification
-	need to send confirmation email to customer to verify their email address and reset their password
-	need to autoassign Vendor as their vendor so that we don't have to do it manually
-	need to auto-assign Vendor with sitebuilder role into their organization

**Comment by timeforcamp** [comment]
Ready to test.
