### ISSUE TITLE
Vendor: Onboarding via organic Time For Camp account creation

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#194]
•	Modify our normal wizard to include a vendor question for customers who sign up organically
-	Do you have a Vendor account number?
If yes, enter it.
If no...
•	Are you interested in learning more about using a vendor for your event apparel needs?

     - If yes...then what?  Email vendor with their customer information???

     - If no…no further action.

**Comment by timeforcamp** [comment]
Complete and pending testing with customer.
