### ISSUE TITLE
Vendor: Customer Tab

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#195]
•	Give vendor the ability to see a customer list of everyone who has them as a vendor.  When they select a customer…shows contact information, account number, who onboarded them (if applicable) etc., maybe even links to that customers completed vendor orders so that they can be found easily
-	This would be where Vendor would manage vendor-specific information…like account number, assigned sales rep, etc.

**Comment by timeforcamp** [comment]
This has been created.
