### ISSUE TITLE
Vendor: Report Access

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#199]
Give vendor access to the reports needed on their side
-	packing list - both
-	orders/products - both

**Comment by timeforcamp** [comment]
This is in the current build, I gave the vendor access to the event dashboard for the store. When you are logged in as a vendor the "stores" tab has each store listed with the ability to "view dashboard" which has the same view the event sponsor has.

**Comment by timeforcamp** [comment]
Complete.
