### ISSUE TITLE
Administrative Fee: Deduct From Camp not working on standard camp

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#20]
Set the camp to Deduct from Proceeds, but registrant still presented with Administrative fee at checkout.

![image](https://user-images.githubusercontent.com/13508954/68802567-c5c70d00-0623-11ea-96ce-c3530016af2e.png)

![image](https://user-images.githubusercontent.com/13508954/68802515-a7f9a800-0623-11ea-9d7b-93db1edb38ae.png)

**Comment by timeforcamp** [comment]
Fixed in the December release.
