### ISSUE TITLE
Vendor: Flyer Upload

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#200]
Vendor may need the ability to upload their current flyer solution so that it is available to the appropriate organization.  Right now we have it where the event sponsor uploads it....but I think it should be vendor who uploads it and then it is available to the event admin on their dashboard.

However...not sure how Gandy would be able to assign the flyer to an event without knowing that event ahead of time.

Something to think about.

**Comment by timeforcamp** [comment]
Updated to managed from vendor order screen.
