### ISSUE TITLE
Product Personalization: Grouping in shopping cart

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#202]
When a customer places an item with personalization in their cart...it gets its own line in the shopping cart...driven by the item type (which happens to have personalization).

However, when a second, similar item is added to their cart (same item/same size/same color) with different personalization...the item is added to the first item quantity without maintaining the unique personalization.

This will be a problem for a parent who is trying to register her two kids to an event and wants them both to get a personalized item with their first name.  They have to create two orders...which will be seen as inefficient and annoying.

**Since we already account for item/size/color when we determine if items will get their own line in the shopping cart or be merged with another....can't we look at personalization as a distinguishing characteristic as well...and sort accordingly?**

**Comment by timeforcamp** [comment]
Fixed in next build.
