### ISSUE TITLE
TFC Content: Event Category

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#203]
We agree that most visitors will probably never see the Time For Camp search screen as they will be more inclined to just go to the organization's home page.  However, we don't show the event category anywhere on that page...or on event details.

This is not a problem with an organization like Bulldog Soccer Camp...where you KNOW exactly what type of event you are signing up for, but could present a problem when you look at organizational use of our system that addresses multiple event categories....like a WALL ISD...who may have soccer, football, softball, baseball, etc. all on there at the same time.

We need to include the event category within each line in the event table at the org home page as well as on the Event Details page.

**Comment by timeforcamp** [comment]
Added this to all the areas above.
