### ISSUE TITLE
Team Event: new_team page

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#238]
We need to change our message about Team Full Pay and Share Pay

![image](https://user-images.githubusercontent.com/13508954/100548403-f6c7af00-3231-11eb-8b7e-a92721e79443.png)

**CHANGE TO**
IMPORTANT:
Payments for Team Full Pay include administrative fees based on the total registration costs for all team attendees.  Payments for Shared Pay teams include administrative fees based on the amount contributed by the team towards each anticipated attendee. These fees must be paid before the registration code is activated. If a team pays by Cash or Check, the calculated registration costs plus administrative fees will be deducted from the event proceeds at the time of purchase.

**Comment by timeforcamp** [comment]
In next build
