### ISSUE TITLE
TEAMS CARDS: for multi-team event

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#240]
Current header colors are not being applied and the cards need to reflect ACTIVE and INACTIVE status in reference to the registration codes.  Would it be possible to have the card header colors trigger off of that flag.

![image](https://user-images.githubusercontent.com/13508954/100548940-9470ad80-3235-11eb-9206-85f83055f0db.png)

RED = INACTIVE (Payment Due)
GREEN = ACTIVE (Paid In Full)
BLACK = refunded / voided

**Comment by timeforcamp** [comment]
Not right now, the cards are triggered off the status of the order. I had to tweak them in the latest build so they should make more sense. These colors are all driven by the skin.

**Comment by DENICHOLS** [comment]
Understood....

What color will the card be if there is a balance due that causes the registration codes to be inactive?  Can we put active/inactive on the card somewhere so that there is a visual of that?

**Comment by timeforcamp** [comment]
This is dependant on what color you set in the skin. Will set a flag on the card that states if the codes are in-active.

**Comment by timeforcamp** [comment]
Card will show code if active and will state Not Active if the codes are not active.
