### ISSUE TITLE
Multi-Team Event: Team Leader

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#245]
A new user who is assigned as a Team Leader has no visibility to the team once he activates his account.  Upon accepting the invitation and setting the password, he is taken to the dashboard where there is no information and no way to switch over to the team using options in the nav bar on the left. 

I think this is where the ATTENDEES menu played a role (that we removed)

![image](https://user-images.githubusercontent.com/13508954/100552055-5762e600-324a-11eb-8727-483a9f4c5375.png)

**Comment by timeforcamp** [comment]
Resolved in current build.

**Comment by DENICHOLS** [comment]
Need clarification on exactly what SHOULD be showing.  With one Team Leader I saw registration widgets on the dashboard, but with another Team Leader, I saw attendees.

**Comment by timeforcamp** [comment]
I have not pushed this to test yet. But will be showing attendees when correct. However if you check the user they should only have one account as a team admin. The only way they could see more is if you used an admin that already is an admin then they also register as a coach. Remember a coach is also now an admin, can’t be a separate account or they have to be invited.

**Comment by timeforcamp** [comment]
resolved in latest build.
