### ISSUE TITLE
Main Image (Mobile View & Desktop View)

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#249]
When viewing sites in production on a mobile device (not inspect in browser) or on a desktop browser,  there is a significant space that exists between the top of the image (regardless if on a carousel or a single image) and the header.  I have tried to manipulate different image settings available in sitebuilder, but am not able to close that space.  This is the case with the Default & Front and Center themes.

On the Staff page...the gap is not as noticeable on desktop views, but is noticed on mobile view

**Default Theme**
![image](https://user-images.githubusercontent.com/13508954/100649937-c99a0000-3308-11eb-9748-c054794ff001.png)

**Front & Center Theme**
![image](https://user-images.githubusercontent.com/13508954/100649985-dd456680-3308-11eb-920f-7c7b4ab77086.png)

**Comment by timeforcamp** [comment]
resolved in current build.

**Comment by DENICHOLS** [comment]
Not resolved in Front and Center theme

![image](https://user-images.githubusercontent.com/13508954/100695265-79498f00-3356-11eb-983e-17ac507bdac8.png)

**Comment by timeforcamp** [comment]
Not the same issue and not pushed up yet. This is due to the carousel not spacing on the front and center theme.
