### ISSUE TITLE
Camp Add-On Inventory Notification

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#25]
Send email to camp administrator when the # of available add-ons is within 10 remaining so that they can order more if need be before just running out.

**Comment by DENICHOLS** [comment]
This may no longer be necessary once we push the Storefront feature as add-ons at that point should not be inventoried items.

**Comment by DENICHOLS** [comment]
However, we may want to integrate something similar for store items.

**Comment by timeforcamp** [comment]
Resolved with new store feature and products.
