### ISSUE TITLE
Header Logo Size Discrepancies

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#251]
**Default Theme:**
Header logo dimension settings within sitebuilder are applied appropriately to the logo when viewed on the organization's home page (in both desktop and mobile view) but **NOT** to the logo in the header when viewing an individual staff bio page.  

Home Page: 100w x 80h
![image](https://user-images.githubusercontent.com/13508954/100653170-9c9c1c00-330d-11eb-95e7-01d7fbe9f2cd.png)

Staff Page: 100w x 100h
![image](https://user-images.githubusercontent.com/13508954/100653272-c05f6200-330d-11eb-85c9-f523ebe43795.png)

**Front & Center Theme**
Header logo dimension settings within sitebuilder DO NOT appear to have any bearing on the logo when viewed on the organization home page or on the staff page when on DESKTOP view.  However, the mobile settings ARE being applied appropriately.

**Comment by timeforcamp** [comment]
resolved in latestet build.
