### ISSUE TITLE
TFC CONTENT > Organization Description

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#259]
When an org signs up and completes the Wizard, they fill out the description of their organization.  There is a note below that field that says **"Please describe your organization in detail. This is only visible to our account team and is used to help us understand the function and design of your events.”**, but we are now publishing that on organization and event pages as a header subtitle within TFC Content. 

If we are going to put a subtitle there…we should give them the ability to edit it within TFC content and not pull from ORGANIZATION description as it is not intuitive as to where that is being pulled from and it contradicts the original intent of that information.

**Comment by timeforcamp** [comment]
In current build.
