### ISSUE TITLE
TFC CONTENT > EVENT DETAILS PAGE > PAGE BACKGROUND COLOR

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#260]
The page background color setting within the EVENT DETAILS PAGE is controlling the HEADER CONTENT background color on the ORGANIZATION PAGE as well.  We don't currently have a setting that allows us to control the HEADER CONTENT BACKGROUND COLOR.

EVENT DETAILS PAGE changes should not impact anything in the header content, which is visible across all pages.

**Comment by timeforcamp** [comment]
In current build.
