### ISSUE TITLE
TFC Content > Navigation Bar: Cart icon/background color (PREVIEW)

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#266]
The settings for cart text / cart background colors do not appear to have any effect on the aesthetic of the cart once applied within the PREVIEW pane, but are applied on the live site.

**Comment by timeforcamp** [comment]
Fixed in next build, also related to #270

**Comment by DENICHOLS** [comment]
Cart background is fixed, but cart text is not.

![image](https://user-images.githubusercontent.com/13508954/103173734-89a03d00-4822-11eb-8d2c-204d72f4fe60.png)
