### ISSUE TITLE
TFC Content: Hamburger Background and Line Color not being applied

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#270]
The color selected for the hamburger background and hamburger line color is not being applied.

**Comment by timeforcamp** [comment]
Changed "Hamburger Text" to "Hamburger Lines" this is ONLY for the hamburger aka just the icon. What you are referring to above is actually the side navigation bar in mobile. It should be using the dropdown menu colors.

**Comment by timeforcamp** [comment]
This should be fixed but might need to test it in a few situations.

**Comment by DENICHOLS** [comment]
These are my settings:

![image](https://user-images.githubusercontent.com/13508954/103486934-15880b00-4dc7-11eb-961a-8d13a038b604.png)

These are my results:
![image](https://user-images.githubusercontent.com/13508954/103486959-3a7c7e00-4dc7-11eb-8b55-56198b7d674e.png)

![image](https://user-images.githubusercontent.com/13508954/103486976-4f591180-4dc7-11eb-9f86-64e6b3d337a4.png)

**Comment by timeforcamp** [comment]
![image](https://user-images.githubusercontent.com/6132268/103578369-0cb53900-4e9c-11eb-851e-80b64ded5c08.png)

I get a totally different view on Test. I wonder if the build had not been pushed before you tested this?

**Comment by timeforcamp** [comment]
![image](https://user-images.githubusercontent.com/6132268/103578459-3bcbaa80-4e9c-11eb-93cd-939775ebf228.png)

**Comment by DENICHOLS** [comment]
This setting does not take effect until an organization is selected for searching.
