### ISSUE TITLE
TFC Content: HEADER

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#272]
The WYSIWYG editor for the "Event Disclaimer or Additional Information" provides enough functionality to serve as the sole entry point for title, disclaimer, etc. within the header.

Accordingly, I think we can eliminate Organizational Title/Description, Organizational Title Color, and Organization Description Color as all of that can be accounted for within the WYSIWYG editor in one place.  The WYSIWYG font colors already overwrite the selected Org title and description colors anyways.

Rename the WYSIWYG Editor section to : **Organization Title & Tagline** and leave the Header Background Color selector as the only option on the page.

![image](https://user-images.githubusercontent.com/13508954/103101361-d397e180-45dc-11eb-8887-04a0bb2f4ecd.png)

**Comment by timeforcamp** [comment]
in next build 12/26/2020
