### ISSUE TITLE
Registration validation error: unknown

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#275]
When trying to submit a registration, the page throws an error "Please review the problem below", but does not indicate WHAT the problem is.

I thought this might be related to only have a free product available, but get the same result even when an upgrade product is available too.

**Comment by timeforcamp** [comment]
This is happening due to the product not having at least one option value set. This is a bug and needs to be addressed.

**Comment by timeforcamp** [comment]
fixed in current build.

**Comment by DENICHOLS** [comment]
Did you put in the logic to prevent the event admin from designating the upcharge item the same as the free item?

**Comment by timeforcamp** [comment]
Yes, I added logic to prevent the upcharge item from being the same as the free item. However, that is not what is causing the issue above. The issue above happens regardless of the free / upcharge item issue.

**Comment by DENICHOLS** [comment]
Closing this issue and entered another to clarify the actual problem
