### ISSUE TITLE
Store: Product Card Header Color not being applied in preview or on live site

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#277]
![image](https://user-images.githubusercontent.com/13508954/103160532-fe7c6400-479b-11eb-80f2-a67be6bbc2cf.png)

![image](https://user-images.githubusercontent.com/13508954/103160538-0d631680-479c-11eb-966a-b1d3b255189d.png)

**Comment by timeforcamp** [comment]
Fixed in next build. 12/26/2020
