### ISSUE TITLE
Header Logo (or deault TFC logo) being used in shopping cart

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#279]
![image](https://user-images.githubusercontent.com/13508954/103161138-fc69d380-47a2-11eb-8d33-6be4696f01a4.png)

No header logo selected within TFC content, but I do have a Navbar logo selected for the SCHOOLTFC organization (TFC Content)

The registration shows the default TFC logo.  Must still be looking at the Header Logo, which is non-existent...which is why TFC is showing up.  

It should be...

![image](https://user-images.githubusercontent.com/13508954/103161176-66827880-47a3-11eb-9da2-083c571ee8ac.png)

**Comment by timeforcamp** [comment]
In next build.
