### ISSUE TITLE
Remove Organization Title/Description & replace with Header Banner for consistent look throughout registration/checkout flow

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#280]
Right now, the header banner is present on the Organization page (along with the header title/description), Event Details, Registration Page and Store Page, but then is replaced on the remaining pages (shopping cart, Billing, and Review Payment) with the header description.  Keep the look and feel consistent and just carry the header banner throughout and only have the header description on the org home page.

**ORG HOME PAGE**
![image](https://user-images.githubusercontent.com/13508954/103173283-88214580-481f-11eb-8212-dd8d16d4dfaa.png)

**EVENT DETAILS**
![image](https://user-images.githubusercontent.com/13508954/103173304-b6068a00-481f-11eb-83e4-e2ea559df059.png)

**REGISTRATION**
![image](https://user-images.githubusercontent.com/13508954/103173312-ca4a8700-481f-11eb-99cd-d0651e2c9b92.png)

**STORE**
![image](https://user-images.githubusercontent.com/13508954/103173332-ef3efa00-481f-11eb-89cd-eb76e0a7bb94.png)

**SHOPPING CART**
![image](https://user-images.githubusercontent.com/13508954/103173377-39c07680-4820-11eb-8cb5-581147f4cdbf.png)

**BILLING**
![image](https://user-images.githubusercontent.com/13508954/103173414-77bd9a80-4820-11eb-8ae3-5505ec63f34b.png)

**PAYMENT**
![image](https://user-images.githubusercontent.com/13508954/103173458-a89dcf80-4820-11eb-843c-a0e8fc43b2ee.png)

**Comment by timeforcamp** [comment]
This is actually by design. It should not have the banner on those screens and it is not intended to have a paragraph on the header.

**Comment by timeforcamp** [comment]
I would not put the logo as the banner image, hence the name banner and not logo. It isn’t a problem to do that but if you use the logo field and the description as the org title and not a paragraph the aesthetics are more consistent as you have the logo and org title on every page. Also I am going to remove the banner on the registration page again for this reason. The banner is only intended to be shown on the org and event Details pages.
