### ISSUE TITLE
Add Event: Team Event > Event start date calendar is non responsive

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#285]
After selecting the registration close date and clicking on the event start date calendar...the calendar appears, but you are not able to select any dates from the calendar.

![image](https://user-images.githubusercontent.com/13508954/103487214-600a8700-4dc9-11eb-8138-53e900c1f103.png)

**Comment by timeforcamp** [comment]
This is due to the request help feature from freshdesk. The javascript is overlaying a selection window over the top of that portion of the screen. If you scroll the page down you can select the data. Not Sure how to fix this without removing the help widget.

**Comment by DENICHOLS** [comment]
Different Freshdesk plans allow for additional customization within the Help Widget including page location.  We may need to look into that in the future if this becomes a bigger issue, but for now, I think we just understand the conflict and help our customers work around it....if/when they run into it.  I only experienced it on a tablet-sized laptop...not standard 14" or larger.  Could just have an odd breakpoint for responsiveness that caused the overlap to occur.
