### ISSUE TITLE
Error when submitting New Customer

### ISSUE THREAD

**Issue by mercedesgrafton** [timeforcamp/time-for-camp#289]
I tried again to add a new customer and after selecting submit, I got the following error:
![image](https://user-images.githubusercontent.com/77077775/103920185-9a7c6880-50d6-11eb-91b0-23abac84813c.png)

After going back, it looks like the customer added correctly, but it is automatically switching me into their account after I submit and gave me that "search" alert.

I assigned as "bug", but not sure what the functionality is supposed to be there.

**Comment by timeforcamp** [comment]
This should just create the customer for you in the folder you are in. It is currently switching you into their account and that is not the intended behavior.
