### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by mercedesgrafton** [timeforcamp/time-for-camp#290]
Received the following error message when trying to access one of my customer folders from the customer tab:
![image](https://user-images.githubusercontent.com/77077775/103922401-5048b680-50d9-11eb-8313-d84d1e109b80.png)

**Comment by timeforcamp** [comment]
This was related to the performance issue that Heroku was having. I have tested it several times and have not seen it again.  Can you confirm it is happening? They have resolved the Heroku issue.
