### ISSUE TITLE
Left Side Navigation Collapses

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#300]
When you select Website, you are able to see the sub menus that are available.  Clicking on TFC Content or Site Builder maintains that state of visibility.  However, once you click on any of the tabs within TFC Content or SiteBuilder, the left side navigation collapses back to default. 

It works when you are on PRESETS, but none of the other tabs.  And now that they are nearly identical as far as the options are concerned...makes it tricky.

It is then unclear if you are working in TFC Content or Site Builder...especially when having to bounce back and forth to see how you have coded different sections, or grabbing color palette values for consistency.

![image](https://user-images.githubusercontent.com/13508954/104109697-37d1cb00-5296-11eb-8850-a6d1d6b9b1b4.png)
![image](https://user-images.githubusercontent.com/13508954/104109726-5e900180-5296-11eb-8027-4ac0105d7202.png)

**Comment by DENICHOLS** [comment]
Navigation still collapses on TFC Content tabs

**Comment by timeforcamp** [comment]
I only fixed sitebuilder yesterday, didn't realize it was doing it for tfc content as well. Stand by
