### ISSUE TITLE
Add Product Image

### ISSUE THREAD

**Issue by mercedesgrafton** [timeforcamp/time-for-camp#309]
Hey!

When I try to add an image in the products section, it doesnt add the image and then when i hit the refresh button in that section, I get this error message
![image](https://user-images.githubusercontent.com/77077775/105550263-da427300-5cc6-11eb-973a-c970cbc7305d.png)

**Comment by timeforcamp** [comment]
There were a couple of issues:

The customer information was not being carried over to the new product which was throwing the main error.
The information for the options selected in the template were not being saved correctly.
These are working and should be good to go for testing.
