### ISSUE TITLE
Error Message When Submitting/Adding New Product

### ISSUE THREAD

**Issue by mercedesgrafton** [timeforcamp/time-for-camp#310]
I am getting the same error message when trying to create a product for a new customer:
![image](https://user-images.githubusercontent.com/77077775/105550987-b7fd2500-5cc7-11eb-929a-a06fca337b88.png)

**Comment by mercedesgrafton** [comment]
I am getting the same error when I try to access the Products tab from the main page on my login (left hand menu)

**Comment by timeforcamp** [comment]
There were a couple of issues:

1. The customer information was not being carried over to the new product which was throwing the main error.
2. The information for the options selected in the template were not being saved correctly. 

These are working and should be good to go for testing.
