### ISSUE TITLE
ERROR: Editing a store item that was in my cart and updating threw error

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#311]
ArgumentError (wrong number of arguments (given 0, expected 1)):

CHURCHTFC - had a registration and an extra shirt in my cart.  I wanted to change the color of the shirt so I edited the item I had added and changed the color selection.  Upon submit, I threw the above error.

FYI...I WAS able to edit the color of the free shirt offered through registration...just not the additional one I added in the store.

**Comment by timeforcamp** [comment]
Updated model method had not been updated in ADO object.
