### ISSUE TITLE
Ensure that Maintenance Screens and Error Screens are mobile responsive

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#49]
Currently the image is not.

![image](https://user-images.githubusercontent.com/13508954/72083254-1925a680-32c7-11ea-9ff3-06e2ece1615f.png)

**Comment by DENICHOLS** [comment]
![image](https://user-images.githubusercontent.com/13508954/74590064-a1871d80-4fd0-11ea-90df-93d22fe115be.png)

Still not quite right.  Looked on phone as well and image is cropped starting at the coaches' elbow

**Comment by timeforcamp** [comment]
you can't shrink the screen like this to view the mobile responsiveness. You have to either put it in a mobile view using chrome or look at it on your phone. What browser did you use on your phone? it looks fine on both of my devices.
