### ISSUE TITLE
Invitation Email Modification to inlcude WHO Invited them and for what camp

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#50]
When a user is invited to be a camp administrator (of any type), we need to include WHO invited them and for What Camp.

Current:
You have been invited to be an Administrator at TimeForCamp.com. If you don't want to accept the invitation, please ignore this email. Your account won't be created until you access the link below and set your password.

**Proposed:**
{DEREK NICHOLS} has invited you to be an Administrator within {CAMP NAME} on TimeForCamp.com. If you don't want to accept the invitation, please ignore this email. Your account won't be created until you access the link below and set your password.

**Comment by timeforcamp** [comment]
Can only include the first and last name of the person sending the invite.
