### ISSUE TITLE
STORE: CONFIGURATION - Notice of Administration Fee to administrator needs to also include notice of flat $ addition

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#67]
The message that displays when an admin turns on their camp and saves it needs to include not only the 6.5% admin fee notice, but also the notice of the additional flat $ addition to the item price.

**Comment by timeforcamp** [comment]
can you provide more details of where this would be? Also, i don't think the per item fee applies to camps as the store product has this information.

**Comment by DENICHOLS** [comment]
Notice of Store Administration Fee: Time For Camp charges an administration fee of 6.50% per transaction plus an additional $1.00 per purchased item, which is automatically added to the item price in the store. This fee is not refundable under any circumstance.
