### ISSUE TITLE
Installment Agreement on Deposit

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#7]
When selecting to pay a deposit and then filling in the amount, you are supposed to confirm the installment agreement.  But if you don't and just click on PROCEED TO CHECKOUT...you get a warning to "Review the problems below", but nothing is shown.  The confirmation checkbox and error message are no longer present...neither is the deposit toggle or deposit amount.

![image](https://user-images.githubusercontent.com/13508954/57586335-25e4c700-74ba-11e9-8bbe-bd8c647f63e5.png)

**Comment by timeforcamp** [comment]
This has been resolved.
