### ISSUE TITLE
(New) Additional Options: Projected High School Graduation Year

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#74]
Provides ability for campers to enter the 4-digit year of their projected High School graduation.  Only need VISIBLE & REQUIRED options for camp administrator.

**Comment by TFCAdmin** [comment]
Limit entry to 4 digits.

**Comment by DENICHOLS** [comment]
Actual HS Graduation date could be in the past, but authentication prevents that entry at this time.
