### ISSUE TITLE
Team Admin - Camper Table

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#79]
Is it possible to add a column in the table called Payment Status, that shows the following based on camper status:

Paid In Full
Balance Due
In Shopping Cart

![image](https://user-images.githubusercontent.com/13508954/74065068-a7ba4000-49b9-11ea-8baa-073140148ba5.png)

I think that this would be beneficial to the team admin without actually giving them the ability to look deeper into the transaction information for the camper.  They could at least tell their campers to finalize their registrations if need be as camp approaches.

**Comment by timeforcamp** [comment]
Only campers that have paid in full show up in this table today.
