### ISSUE TITLE
STORE: USER VIEW - Main store page product card

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#88]
Give the header background portion of the card a little more color so that it stands out more from the cod body.  

![image](https://user-images.githubusercontent.com/13508954/74110110-44621680-4b4f-11ea-95a8-130156130e3d.png)

![image](https://user-images.githubusercontent.com/13508954/74110128-8723ee80-4b4f-11ea-9e20-f865c5734e59.png)

**Comment by timeforcamp** [comment]
Added style options to the product so the admin can change the card style as needed.
