### ISSUE TITLE
SHOPPING CART: Camp logo needs to be smaller in order to fit in card properly

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#89]
![image](https://user-images.githubusercontent.com/13508954/74110167-dd912d00-4b4f-11ea-9f0d-02605bd3a9f6.png)

**Comment by timeforcamp** [comment]
i am on the test site and I cannot get the above to render the same way. Can you provide more re-create steps? I am using the existing camp that was created?
