### ISSUE TITLE
Shopping Cart Redirect Error

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#9]
After applying payment (regardless if the order has deposits or not), you are redirected back to the shopping cart where you see an alert saying that "Your Cart is empty you cannot check out."

![image](https://user-images.githubusercontent.com/13508954/57623596-aad0ee80-7555-11e9-9a64-b7ab3abef9fd.png)

**Comment by timeforcamp** [comment]
This has been resolved.
