### ISSUE TITLE
STORE: Stand alone storefront with vanity URL

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#90]
If an organization only wanted to use the Store feature...say a high school spirit club that wanted to sell merchandise....

Would there be any way for them to have their own vanity URL just for the store.

Like rattlerspirit.com for example, that would take them straight to their storefront.  Or, do they only have the option to go to something like https://timeforcamp.com/store/show/xxxx

**Comment by timeforcamp** [comment]
right now it is not possible. We could add a new vanity url into the configuration but it would require 2 dns entries and another domain registration on the part of the camp administrator.
