### ISSUE TITLE
Summary Screen: USER VIEW - add note that deposit does not apply to store items.

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#92]
Add a note that the deposit does not apply to admin fees, store items, or taxes.

![image](https://user-images.githubusercontent.com/13508954/74114981-8fd9ec00-4b72-11ea-80ea-9ecc77bd6e08.png)

**Comment by timeforcamp** [comment]
This is correct, we do not allow deposits on store items.
